version: "3.7"
services:
  proxy:
    image: "traefik:v2.1"
    command:
      # proxy
      - "--api.insecure=false"
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=${TLS_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      # API
      # - "traefik.http.routers.api.rule=Host(`traefik.${URL}`)"
      # - "traefik.http.routers.api.service=api@internal"
      # - "traefik.http.routers.api.middlewares=auth"
      # - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTHSTRING}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "proxy_letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  backend_proxy:
    image: jwilder/nginx-proxy
    environment:
      - DHPARAM_GENERATION=0
    expose:
      - 80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${URL}`)"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend-http.entrypoints=web"
      - "traefik.http.routers.backend-http.rule=Host(`${URL}`)"
      - "traefik.http.middlewares.backend-https.redirectscheme.scheme=https"
      - "traefik.http.routers.backend-http.middlewares=backend-https@docker"
    depends_on:
      - backend

  backend:
    image: docker.pkg.github.com/corridors-of-time-transcription/puzzlepieces/puzzlepieces:${IMAGE_TAG}
    restart: always
    command: uwsgi --ini /usr/src/app/uwsgi.ini
    expose:
      - 8000
    environment:
      - DEBUG=${IS_DEBUG}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${URL}
      - SQL_ENGINE=django.db.backends.mysql
      - SQL_DATABASE=puzzlepieces
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=db
      - SQL_PORT=${SQL_PORT}
      - DATABASE=mysql
      - VIRTUAL_HOST=${URL}
      - VIRTUAL_PORT=8000
      - VIRTUAL_PROTO=uwsgi
    labels:
      -  "traefik.enable=false"

    depends_on:
      - db

  db:
    restart: always
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_PASSWORD_ROOT}
      - MYSQL_DATABASE=puzzlepieces
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
    volumes:
      - db_mysql:/var/lib/mysql
    labels:
      - "traefik.enable=false"

volumes:
  proxy_letsencrypt:
  db_mysql:
